# Generated by Django 6.0.1 on 2026-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="994XXXXXXXXX formatında (başında + olmadan)",
                        max_length=32,
                    ),
                ),
                ("working_hours", models.CharField(blank=True, max_length=120)),
                ("map_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
