# Generated by Django 6.0.1 on 2026-01-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="994558811339",
                        help_text="Yalnız rəqəmlər. Məs: 994558811339 (başında + olmasın).",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
