# Generated by Django 6.0.1 on 2026-02-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_sitecontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="branches/"),
        ),
    ]
