# Generated by Django 6.0.1 on 2026-02-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_branch_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="phone",
        ),
    ]
